### ISSUE TITLE
there is no item named html/messages in the archive

### ISSUE THREAD

**Issue by Seantimez** [jsharkey13/facebook_message_parser#3]
Looks like the archive file structure has changed or is different in my locale.

Downloaded archives from facebook do not contain this file (html/messages). The zip file contains a messages folder with separate folders for each facebook user's messages. Each of those folders contains a message.html file There is no html folder.

Additionally, there are no files named messages.htm in the downloaded archive. I attempted to change one of the message.html files to messages.htm and placed it in the parser directory, but it couldn't be parsed.

I'd love to use this parser! It does exactly what I need to do.

Can it be updated to match the new archive/file structure?

**Comment by jsharkey13** [comment]
I'm going to deprecate this parser soon; Facebook has radically altered the structure of the export. The only issue is that the new JSON export keeps changing format, and doesn't contain all the information the old exports used to.
I've got some code that works with the new format, but until Facebook settle on the format I've been holding off creating a new repo. I'll have another look this week and try tidying up and uploading that code. I'll keep this issue updated with progress!

[EDIT: It may be that the JSON format is enough for you, rather than the HTML, depending on your use case and technical prowess.)

**Comment by Seantimez** [comment]
I understand - I imagine constant changes to format would require constant updates to the parser. I have the archive in both HTML and JSON. Use case marries up to the example in the readme.md. My experience with JSON is minimal, so my technical prowess there matches my experience.

If you have code that works with either in the new format, I'd love to run it.  And I'll keep a copy of the current version to compare the differences.

Thank you for your excellent work on this project. I look forward to hearing from you.

**Comment by Seantimez** [comment]
feel free to write sean+github at seanward.org

**Comment by jsharkey13** [comment]
@Seantimez 
Some working code is here: https://gist.github.com/jsharkey13/d60b7b421e08c98d426d03c39f8b4a12

It's now Python 3, no longer Python 2.7, due to the deprecation of the latter. It's very much based on the code in this repository.

You'll want both files, and there's some information in my comment at the bottom of the Gist. I can't promise it'll keep working, and it may have some bugs; but it's a useful place to start. I'm going to mark this repo as no longer maintained.

**Comment by jsharkey13** [comment]
Closing this issue and marking the repo as archived.
